export default [
  { path: '/user', layout: false, routes: [{ path: '/user/login', component: './User/Login' }] },
  { path: '/welcome', icon: 'smile', component: './Welcome' },
  { path: '/user_manage', icon: 'user', component: './User/Manage', name: '用户管理' },
  {
    path: '/addSalesRecord',
    icon: 'moneyCollect',
    component: './SalesRecord',
    name: '添加销售记录',
  },
  { path: '/updateSalesRecord/:recordId', component: './SalesRecord/UpdateSalesRecord' },
  {
    path: '/salesRecords',
    icon: 'moneyCollect',
    component: './SalesRecord/SalesRecordList',
    name: '销售记录',
  },
  { path: '/clientManage', icon: 'user', component: './ClientManage', name: '客户管理' },
  { path: '/clientManage/add', component: './ClientManage/add' },
  { path: '/clientManage/update/:clientId', component: './ClientManage/update' },
  {
    path: '/admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      { path: '/admin', redirect: '/admin/sub-page' },
      { path: '/admin/sub-page', component: './Admin' },
    ],
  },
  { path: '/mindView/:rootUid', component: './MindView', name: '思维导图', layout: false },
  // { path: '/mindView', icon: 'crown', name: '思维导图' },
  { path: '/caseManage', component: './CaseManage', name: '用例管理', icon: 'database' },
  // { icon: 'table', path: '/list', component: './TableList', name: '列表页' },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
];
